## where to store your database, default is your system data directory
## linux: ~/.local/share/atuin/history.db
## macOS: ~/Library/Application Support/atuin/history.db
# db_path = "~/.history.db"

## where to store your encryption key, default is your system data directory
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory  
# session_path = "~/.session"

## date format used, either "us" or "iso" 
# dialect = "iso"

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = false

## address of the sync server
sync_address = "https://api.atuin.sh"

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may be longer
## set it to 0 to sync after every command
sync_frequency = "10m"

## which search mode to use
## possible values: prefix, fulltext, fuzzy
search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "global"

## With workspace filtering enabled, Atuin will filter for commands executed
## in any directory within a git repository tree (git root). Defaults to false
workspaces = true

## which style to use
## possible values: auto, full, compact
style = "compact"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 15

## enable or disable showing a preview of the selected command
## useful when the command is longer than the terminal width and is cut off
show_preview = true

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
exit_mode = "return-original"

## possible values: emacs, subl
word_jump_mode = "emacs"

## characters that count as a part of a word
word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"

## number of context lines to show when scrolling by pages
scroll_context_lines = 1

## use ctrl instead of alt as the shortcut modifier key for numerical UI shortcuts
## alt-0 .. alt-9
ctrl_n_shortcuts = false

## default history list format - can also be specified with the --format arg
history_format = "{time}\t{command}\t{duration}"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
history_filter = [
   "^secret-cmd",
   "^innocuous-cmd .*--secret=.+"
]

## prevent commands run with cwd matching any of these regexes from being written
## to history. Note that these regular expressions are unanchored, i.e. if they don't
## start with ^ or end with $, they'll match anywhere in the command.
cwd_filter = [
   "^/very/secret/area"
]

## Configure the maximum height of the preview to show.
## Useful when you have long scripts in your history that you want to distinguish
## by more than the first few lines.
max_preview_height = 4

## Configure whether or not to show the help row, which includes the current Atuin
## version (and whether an update is available), a keymap hint, and the total
## amount of commands in your history.
show_help = true

## Configure whether or not to show tabs for search and inspect
show_tabs = true

## Invert the UI - put the search bar at the top , Default to `false`
invert = false

## Defaults to true. This matches history against a set of default regex, and will not save sensitive commands to history.
## Defaults to true.
secrets_filter = true

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
## This matches the default behaviour of bash/zsh up-arrow history search.
enter_accept = true